### ISSUE TITLE
Cannot run m3u_gen_acestream.py

### ISSUE THREAD

**Issue by cmpek** [SCP002/m3u-gen-acestream#4]
Hi.
Ubuntu 16.04.5 LTS

Python 2.7.12
$ python m3u_gen_acestream.py
  File "m3u_gen_acestream.py", line 20
    def main() -> None:
               ^
SyntaxError: invalid syntax

Python 3.5.2

$ python3 m3u_gen_acestream.py
  File "m3u_gen_acestream.py", line 21
    channel_handler: ChannelHandler = ChannelHandler()
                   ^
SyntaxError: invalid syntax

**Comment by cmpek** [comment]
sorry after install python 3.7 it worked.
You can specify the minimum version python in the first line )))

**Comment by SCP002** [comment]
Yep. Thanks for this issue. I will add a note about it :+1:

**Comment by SCP002** [comment]
Done with https://github.com/SCP002/m3u-gen-acestream/commit/882aeb46d66dbba6b2b91e205cbb7b1b94905789
